name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 1 * * 1'

jobs:
  update-readme:
    name: update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: xinzhuohkust/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: false
